### ISSUE TITLE
Delay parameter shown in GUI not used after system restart

### ISSUE THREAD

**Issue by hanoba** [badaix/snapdroid#11]
I am running the Android client on the Bluestacks Android Emulator. 

I noticed a potential bug in the Android SnapClient: I have to re-enter the delay parameter after every restart of Bluestacks. It seems that the stored delay parameter shown in the Snapclient GUI is not taken into account after a system restart.

**Comment by badaix** [comment]
This bug has been fixed in Snapcast v0.20
