### ISSUE TITLE
Can't install app

### ISSUE THREAD

**Issue by marcianito** [badaix/snapdroid#12]
Hey!

Snapcast is a great project and I am sucessfully using it at home. Thanks for this awesome development!

The Android app though can't be successfully installed. I tried both version 14 and 15 but after trying to install, Android just states "App not installed". Did someone experience the same or similar problems?

I am running Android 8.01 using Lineage OS 15.1 on a FP2.

Any help would be highly appreciated!
Thanks!

**Comment by badaix** [comment]
is "adb install" saying "App not installed"?

**Comment by badaix** [comment]
please reopen if it's still an issue
