### ISSUE TITLE
MAC is missing

### ISSUE THREAD

**Issue by stephankellermayr** [badaix/snapdroid#19]
When i connect a smartphone to the snapserver, the MAC is recognized as `00:00:00:00:00:00` in `/var/lib/snapserver/server.json`. Everything works normally and i can control the volume, but when i connect a second smartphone (same brand/model), the volume control is applied to both devices. They just act as they were one single snapclient, and they are both identified with the same name and are listed as one item.
(v0.17.1 directly installed from google playstore)

**Comment by badaix** [comment]
please try the [0.17.1.1](https://github.com/badaix/snapdroid/files/4060657/Snapcast_0.17.1.1.apk.zip) from issue #16. It will not fix the MAC address, but will create a unique ID.

**Comment by stephankellermayr** [comment]
0.17.1.2 is working fine, thanks!
