### ISSUE TITLE
Android App can't connect to Snapserver host

### ISSUE THREAD

**Issue by JorgN** [badaix/snapdroid#21]
I have 3 instances of Snapcast running on Raspberry Pi3 with Volumio and Hifiberry dacs and AMP. Snapcast appears to be running fine and all I can find one instance in the other instance as a host. So the hosts seem to be online and working fine.

However: when I use you Android app I can't find any Snapserver host.
- Scanning for server gives no response
- Using the hostname like it appears in the Volumio plugin (also tried for upper case / lower case / checked typos). All does not help ("error unknown host")
- when I use the host IP (in my case 10.0.0.xx) I get the following error: "failed to connect to 10.0.0.xx (port 1704 from ;; (port 39970): connection failed: ECON.."

All my devices are in the same WIFI network.

Any help would be great!

**Comment by derWeihnachtsmann** [comment]
Does the snapserver pull out some logs when you are trying to connect to it?

**Comment by badaix** [comment]
Can you check if your phone can see the server and the other devices in your LAN?
E.g. with https://play.google.com/store/apps/details?id=com.overlook.android.fing

**Comment by slatour007** [comment]
Was this ever solved?  I have snapcast installed with/over Volumio.  Having the same issue trying to connect with an Android phone.  I can see my server and can control Volumio with the phone but snapcast does not see server and has errors when i force the server name or ip address.

Could it be because it is an older phone running Android 6?

**Comment by badaix** [comment]
Maybe the "errors" give an indication of what's not working.
Can you connect with a Linux client? Or can you connect Android with manually started Linux Snapcast server?

**Comment by slatour007** [comment]
Fixed it.

I had the same error as JorgN.

I reinstalled everything from scratch.  I used the command line for installation instead of the "Plugin install" provided by the Volumio GUI.

Thanks

**Comment by badaix** [comment]
Closed due to inactivity
