### ISSUE TITLE
24-Bit Stream Does Not Play

### ISSUE THREAD

**Issue by jbfunk** [badaix/snapdroid#22]
Using a Pixel 3 running Android 10 and Snapdroid 0.17.1.2 (apk downloaded from the releases page), playback will not start with 24-bit streams. 16-bit streams (from the same server with the same number of channels and sampling rate) play fine.

**Comment by badaix** [comment]
Please try [v0.17.1.3](https://github.com/badaix/snapdroid/releases/tag/v0.17.1.3) 
The log tag for errors changed from `Err` to `Error` in latest Snapclient, and so Snapdroid didn't parse the error messages correctly.
When using 24 bit on my phone, I now get the error message
```
Controller::onException: Init failed, operation: Engine::CreateAudioPlayer, result: SL_RESULT_CONTENT_UNSUPPORTED(9)
```

which simply means that the (24 bit) content is not supported by the DAC.

**Comment by jbfunk** [comment]
Thank you so much for so quickly following-up on this and releasing a fix. I now have the same error behavior as you describe.

Are there any plans to perhaps implement conversion of the bit depth down to 16 from 24 (or higher) on Android in the future (even if it's just truncation or rounding)? I know this is handled via, eg, ALSA on linux and not by Snapclient itself, but practically speaking I would like to be able to have just one higher bit-depth stream rather than both a 24-bit and 16-bit version.

Thanks again.

**Comment by badaix** [comment]
Actually, I'm planning to add resampling capabilities into the v0.19 (v0.18 is will be released soon). I've already a prototype using lobsoxr to resample the audio signal to the ["native samplerate"](https://developer.android.com/reference/android/media/AudioManager.html#PROPERTY_OUTPUT_SAMPLE_RATE). Libsoxr can not only resample but can also requantize to 16 bit.

**Comment by jbfunk** [comment]
Thanks--looking forward to it. Nice to be using libsoxr also as it seems like it's a quite high quality resampler.
