### ISSUE TITLE
Buzzing tone when stream interrupted or mopidy server restarted

### ISSUE THREAD

**Issue by linker3000** [badaix/snapdroid#24]
**Phone**: Samsung Galaxy S10
**OS**: Android 10, Kernel 4.14.113-18242812, Build QP1A.190711.020.G973FXXS5CTD1, Security patch level May 2020.
**Snapcast client for Android:** v0.19.0
**Back-end**: Mopidy 3.0.2-1 / Mopidy-MPD 3.0.0-1 + Extensions. 
**Mopidy output stream**: output = audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! wavenc ! filesink location=/tmp/snapfifo

**Symptom**: Restarting the Mopidy back-end, changing current playing item (via a Web front-end), or roaming between in-home wifi points often causes the app to emit a continuous buzz until the app's stop button is pressed. 

**Steps to reproduce:** 

1. Be playing something.
2. Hit pause on a Mopidy Web interface or push something to 'play now' from a different source (eg: be playing a file from the server and switch to a radio stream) or on the Mopidy server, issue a systemctl restart mopidy (eg: after a config update).

Sound Sample: https://github.com/linker3000/Resources/blob/master/snapdroid-noise.m4a

**Comment by badaix** [comment]
This should be fixed in the upcoming v0.20, as discussed in #23 , can you please check the issue is resolved in this version [Snapcast_0.19.0.1_1903_full_wake_lock.apk.zip](https://github.com/badaix/snapdroid/files/4314917/Snapcast_0.19.0.1_1903_full_wake_lock.apk.zip)?

**Comment by badaix** [comment]
Update: please try the updated build, based upon the current develop branch, i.e. v0.20 release candidate
[Snapcast_0.19.90.0.apk.zip](https://github.com/badaix/snapdroid/files/4715966/Snapcast_0.19.90.0.apk.zip)

You must unzip and install the APK using `adb`. Unfortunately, it's not allowed to upload `apk` files in GitHub's issue tracker, so I have to zip them. It's signed with the same key used in the PlayStore, so future updates will work seamlessly.

**Comment by linker3000** [comment]
No buzzing after 30 minutes of testing. Sounding good thanks. Will poke it for a bit more.

**Comment by linker3000** [comment]
Cannot reproduce now so good to close. Thanks for the quick turnaround.
