### ISSUE TITLE
Feature Request: stream favorites

### ISSUE THREAD

**Issue by Torgee** [badaix/snapdroid#29]
Heyo!
I'd really like to have 1-click possibility to switch between 2 or 3 streams. I use 2 different streams for 2 different spotify accounts and we switch between those regularly. 
Right now, I need 4 clicks: 
 - select group
 - click on stream
 - select new stream
 - leave group

Would be nice to have the option to select streams to appear on the main page (extra row below the current stream of the gorup?). That can then be activated with just one click.

**Comment by badaix** [comment]
Have you considered using a [meta source](https://github.com/badaix/snapcast/blob/master/doc/configuration.md#meta) fed by your different spotify accounts?
It will automatically select the actively playing spotify stream.

**Comment by Torgee** [comment]
Oh, didn't knew about the meta source, will definitely help, thx!
Unfortunately doesn't fit for all use cases, but helps for some.
With e.g. 2 groups setup, say "livingroom/kitchen" and "bedroom", it's a lot of clicks if i want to swap streams between both groups.

**Comment by badaix** [comment]
In Snapdroid you can change the stream from the main UI

**Comment by Torgee** [comment]
With less clicks then described above?

**Comment by badaix** [comment]
Just browse to `http://<snapserver host>:1780` and try it.
And as always: PRs to Snapdroid are welcome.

**Comment by Torgee** [comment]
Ah, you meant snapweb - tried it for the first time just now, and yes, there its much quicker, nice, thx.
I think I'm happy now :) closing

**Comment by badaix** [comment]
I think your point is valid, but good that snapweb will do for you. I will not have the time to change this in Snapdroid in the near future.
