### ISSUE TITLE
Client not show

### ISSUE THREAD

**Issue by triseaux** [badaix/snapdroid#33]
Hello, first happy new year and you do really great work on this app.

I have 2 RSPI with balenasound all work perftectly.
When i use snapdroid, i can see mi master player and can mut/unmute and volume +/-.

If i use multiple player, 1 master and 1 client, i can use it for master but mi client dont show on app (android and windows snap.net).

When i publish music on mi master and all mi player is online i can hear sound on all mi room, but i want to volume +/- on each room.

Do you have any idea to how see mi master and client ?

Thx, have a good day.

**Comment by badaix** [comment]
I don't know how this balena is working. If the missing client is also not showing up in snap.net, then is seems not to be a snapdroid issue. Please ask the balena support.
