### ISSUE TITLE
question: intent for tasker

### ISSUE THREAD

**Issue by jimydirektsaft** [badaix/snapdroid#34]
Hi! 
I'd like to toggle pause/play through an intent by using Tasker.
If this is possible could you please tell me which intent I can use?

Thank you

**Comment by stijnvdb88** [comment]
Hi! if the above PR gets merged in, you should be able to use that to achieve what you're asking for :) 

When adding the intent in Tasker (System -> Send Intent), use these settings:
* Action: `ACTION_START`
* Extra: `EXTRA_HOST:ip_here`
* Extra: `EXTRA_PORT:1704`
* Package: `de.badaix.snapcast`
* Class: `de.badaix.snapcast.SnapclientService`
* Target: `Service`

**Comment by Chreece** [comment]
V. 0.24.0.0 Snapcast Android on Samsung Flip3
Neither of the actions work

**Comment by StaleLoafOfBread** [comment]
I came across this bug trying to control snapdroid via tasker. 

@Chreece  you need to download a newer version of snapdroid. I'm not sure if this made it into v0.25.0.0 but I did successfully use it with my OnePlus 7pro. I already had disabled battery optimization and it worked when it was already closed. Though the play / stop icon in app did not update. 

This was on v0.26.0.0 which I got from the actions artifacts. https://github.com/badaix/snapdroid/suites/5195143335/artifacts/158372819

I'm not sure why the Google play store version is still at v0.24.0.0.

**Comment by ianwood** [comment]
Could someone drop a play (or stop) intent into the following format for me? This is the format used by wallpanel.xyz as shown here: https://wallpanel.xyz/docs/launch-external-apps

I don't use intents much. I've tried several combinations of the above but I am clearly missing something. 

intent:#Intent;launchFlags=0x10000000;component=com.ringapp/.ui.activities.LoginActivity;end
