### ISSUE TITLE
Can connect with IP but not with hostname

### ISSUE THREAD

**Issue by guix77** [badaix/snapdroid#38]
Hi,

Snapdroid 0.24.0 detects my Snapcast server by its hostname and prefills the host field, and the ports fields (1704+1705). But it can not connect to the server.

Using the IP of the server instead of the hostname works. With other clients such as https://github.com/cristianpb/muse, using the hostname works. Everything else seems fine, though :)

My Snapserver is v0.23.0 (cannot compile the v0.24.0). Previously it was v0.15.0 and Snapdroid 0.24.0 was working with it too.

Also, thanks for this very cool stuff !

**Comment by Nuesel** [comment]
For Snapdroid 0.24.0, DNS/hostname resolution does not work. But the most recent builds support resolving the IP address, e.g.
https://github.com/badaix/snapdroid/actions/runs/1802461396

**Comment by badaix** [comment]
[Snapdroid v0.26.0](https://github.com/badaix/snapdroid/releases/tag/v0.26.0) is now released
