### ISSUE TITLE
Android client: Need to scroll for second group

### ISSUE THREAD

**Issue by badaix** [badaix/snapdroid#5]
_From @derglaus on April 5, 2018 20:0_

In my Android client, only the snapclients in the first group are shown initially on the display. I need to scroll for the other clients, even if there is enough space. (seems like the height of the box to display the clients is calculated based on the first group and not the available space)
I use Android 7.1.1

_Copied from original issue: badaix/snapcast#381_

**Comment by armageddon421** [comment]
I have this issue on the play store version (it shows 0.14.0.14) but not in the app from the releases here (0.14.0)

**Comment by badaix** [comment]
So I assume that this is only a problem of the play store version (which not maintained by me)
