### ISSUE TITLE
Unable to change latency with the new update

### ISSUE THREAD

**Issue by chicco-carone** [badaix/snapdroid#64]
I just updated the android client to the latest version and if i try changing the latency it doesn't get saved on the server so it has no affect. I can change the latency without issues from snapweb and the python-snapcast library.

I'm running the latest snapcast-git package from the aur on an arch vm in proxmox
 
Here is what happens when i try changing the latency. (tried multiple phones too with the same result)
https://github.com/badaix/snapdroid/assets/66080458/019a11cf-37af-48f7-b8e2-7f31a066f3b5

**Comment by badaix** [comment]
Looks like the same issue as #63 
I've reverted the commit 0c12b3365ea723ad1f22165a24830aa628232d33, please try the CI built:
https://github.com/badaix/snapdroid/actions/runs/8774949825

**Comment by chicco-carone** [comment]
I just tried the latest built one and it has the same issue

**Comment by badaix** [comment]
Should be fixed now with 21c7389e61e0e9e10b6dac13fc8639798c891810, please try this CI build: https://github.com/badaix/snapdroid/actions/runs/8784143765

**Comment by badaix** [comment]
Fixed in [Snapdroid v0.28.0.1](https://github.com/badaix/snapdroid/releases/tag/v0.28.0.1)
