### ISSUE TITLE
mute button missing

### ISSUE THREAD

**Issue by franconianmetal** [badaix/snapdroid#65]
0.28.0.1 has no mute button available
0.27.0 has so

webifs in both show mute button

![Screenshot_20240422_203116_Snapcast.jpg](https://github.com/badaix/snapdroid/assets/18643293/3c8ba542-00d9-4efc-8920-afbb59dfc38d)

can you pls re-add in new version?

**Comment by badaix** [comment]
Fixed in [v0.28.0.2](https://github.com/badaix/snapdroid/releases/tag/v0.28.0.2)

**Comment by franconianmetal** [comment]
such a quick response, thanks!
