### ISSUE TITLE
release link to apk missing on readme.md

### ISSUE THREAD

**Issue by ghost** [badaix/snapdroid#8]
I could not find a link to download the apk for the 0.14 release on this project.
Only the "snapcast" project homepage features  a link - I wouldn't have found the "release" tab under "code" otherwise.

Thanks for your work!

**Comment by badaix** [comment]
well, the readme is admittedly quite sparse at the moment, but there for every project on GitHub a link to the release page of the project (if the project has releases).
![image](https://user-images.githubusercontent.com/10322999/40423308-6d887582-5e92-11e8-9ce8-873e828850a2.png)

**Comment by badaix** [comment]
I will keep this issue open as a reminder that I anyways should put some more text in the Readme

**Comment by mray** [comment]
Unfortunately this specific sub-tab of "code" does not appear on the mobile version on github. :(

**Comment by johanbaaij** [comment]
@ghost 'desktop version' link is on the bottom right of the page :slightly_smiling_face:.

**Comment by badaix** [comment]
Link is finally added :)
